all:
	(cd timerLib; make install)
	(cd lcdLib; make install)
	(cd shapeLib; make install)
	(cd p2swLib; make install)
	(cd circleLib; make install)
	(cd frogger; make install)

clean:
	(cd timerLib; make clean)
	(cd lcdLib; make clean)
	(cd shapeLib; make clean)
	(cd p2swLib; make clean)
	(cd circleLib; make clean)
	(cd frogger; make install)
	rm -rf lib h
